# This workflow relies on actions/cache to store the hak dependency artifacts as they take a long time to build
# Due to this extra care must be taken to only ever run all build_* scripts against the same branch to ensure
# the correct cache scoping, and additional care must be taken to not run untrusted actions on the develop branch.
on:
  workflow_dispatch:
    secrets:
      APPLE_ID:
        required: false
      APPLE_ID_PASSWORD:
        required: false
      APPLE_TEAM_ID:
        required: false
      APPLE_CSC_KEY_PASSWORD:
        required: false
      APPLE_CSC_LINK:
        required: false
    inputs:
      version:
        type: string
        required: false
        description: "Version string to override the one in package.json, used for non-release builds"
      sign:
        type: string
        required: false
        description: "Whether to sign & notarise the build, requires 'packages.element.io' environment"
      base-url:
        type: string
        required: false
        description: "The URL to which the output will be deployed."
      blob_report:
        type: boolean
        required: false
        description: "Whether to run the blob report"
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write
  packages: write
  actions: read


jobs:
  build:
    runs-on: macos-14
    environment: packages.element.io
    steps:
      - uses: actions/checkout@v4

      - name: Debug Repository Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository Name: ${{ github.event.repository.name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Git remote info:"
          git remote -v || echo "No git remotes found"

      - name: Cache .hak
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('hakHash', 'electronVersion') }}
          path: ./.hak

      - name: Install Rust
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "yarn"

      - name: Check Node.js version
        run: |
          echo "Node.js version:"
          node --version
          echo "npm version:"
          npm --version
          echo "yarn version:"
          yarn --version

      - name: Install Dependencies
        run: |
          echo "Installing Node.js dependencies..."
          yarn install --frozen-lockfile
          echo "Installing Python setuptools..."
          pip3 install setuptools

      - name: Fetch Element Web
        run: |
          echo "Fetching Element Web package..."
          yarn run fetch --noverify --cfgdir "" develop
          echo "Creating webapp.asar..."
          yarn run asar-webapp

      - name: Build Natives
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn build:native:universal

      - name: Build App (Signed)
        run: |
          echo "Building signed macOS app..."
          yarn build:universal --publish never
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.APPLE_CSC_LINK }}
          ED_NIGHTLY: ${{ inputs.version }}



      - name: Create GitHub Release and Upload Signed DMG
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
        run: |
          # Find the signed DMG file
          DMG_FILE=$(find dist -name "*.dmg" -type f | head -n 1)
          if [ -z "$DMG_FILE" ]; then
            echo "No signed DMG file found in dist directory"
            ls -la dist/
            exit 1
          fi
          
          echo "Found DMG file: $DMG_FILE"
          
          # Create release tag based on timestamp
          RELEASE_TAG="v$(date +'%Y.%m.%d')-build-${{ github.run_number }}"
          
          # Create release and upload signed DMG
          gh release create "$RELEASE_TAG" \
            --title "SOC Connect Desktop $RELEASE_TAG" \
            --notes "🔐 Signed macOS build from commit ${{ github.sha }}

          **Features:**
          - ✅ Code signed with Apple Developer Certificate
          - ✅ Notarized for macOS Gatekeeper
          - ✅ Custom SOC Connect UI from chat.socjsc.com
          - ✅ Universal binary (Intel + Apple Silicon)
          
          **Installation:**
          Simply download and install - no security warnings!" \
            --draft \
            "$DMG_FILE"
